name: Chainplan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15734647656790912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#aaaca7'
    - '#b25415'
    - '#30312c'
  brandStrength: 0.024969411315396428
  lightness: 0.19970409525558352
  saturation: 0.9747298371512443
  rhythmicContrast: 0.04454348515719175
purpose: []
